/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project215;

import java.awt.Component;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;

/**
 *
 * @author MD Khairul Hasan
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    Integer y = 0;
    String x = "";

    public User() {
        initComponents();
        //  x = (String) jcb1.getSelectedItem();
        // y = jnumBag.getText();
    }
    // Price pr = new Price()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFull = new javax.swing.JPanel();
        jPanel1st = new javax.swing.JPanel();
        jlBG = new javax.swing.JLabel();
        jlBag = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox<>();
        jbtnOK = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jnumBag = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelFull.setBackground(new java.awt.Color(0, 51, 102));

        jPanel1st.setBackground(new java.awt.Color(0, 51, 102));

        jlBG.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        jlBG.setForeground(new java.awt.Color(255, 255, 255));
        jlBG.setText("Enter needed Blood Group");

        jlBag.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        jlBag.setForeground(new java.awt.Color(255, 255, 255));
        jlBag.setText("Enter Number of Bags");

        jcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jcb1.setBorder(null);
        jcb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jbtnOK.setBackground(new java.awt.Color(204, 204, 255));
        jbtnOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnOK.setText("OK");
        jbtnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnOKMouseClicked(evt);
            }
        });

        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1stLayout = new javax.swing.GroupLayout(jPanel1st);
        jPanel1st.setLayout(jPanel1stLayout);
        jPanel1stLayout.setHorizontalGroup(
            jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1stLayout.createSequentialGroup()
                .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1stLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlBag, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBG, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jnumBag)))
                    .addGroup(jPanel1stLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jbtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbtnBack)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1stLayout.setVerticalGroup(
            jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1stLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBG, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1stLayout.createSequentialGroup()
                        .addComponent(jlBag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1stLayout.createSequentialGroup()
                        .addComponent(jnumBag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFullLayout = new javax.swing.GroupLayout(jPanelFull);
        jPanelFull.setLayout(jPanelFullLayout);
        jPanelFullLayout.setHorizontalGroup(
            jPanelFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1st, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFullLayout.setVerticalGroup(
            jPanelFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullLayout.createSequentialGroup()
                .addComponent(jPanel1st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFull, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnOKMouseClicked

        x = (String) jcb1.getSelectedItem();
        y = Integer.parseInt(jnumBag.getText());

        File f = new File("C:\\Users\\MD Khairul Hasan\\Desktop\\Donors_Details.txt");
        String n = "";
        String b = "";
        String g = "";
        String a = "";
        String d = "";
        String m = "";
        String blgr = "";
        String bgs = " ";
        Scanner s = null;

        try {
            if (f.exists()) {
                s = new Scanner(new File("C:\\Users\\MD Khairul Hasan\\Desktop\\Donors_Details.txt"));

                Double p, q;
                while (s.hasNext()) {
                    //   s.useDelimiter("[, \n] ");
                    n = s.next();

                    b = s.next();
                    g = s.next();
                    a = s.next();
                    d = s.next();
                    //System.out.println("fff");
                    m = s.next();
                    blgr = s.next();
                    bgs = s.next();

                    p = Double.parseDouble(bgs);
                    q = Double.parseDouble(jnumBag.getText());

                    if (blgr.equalsIgnoreCase((String) jcb1.getSelectedItem())) {
                        if (p >= q) {
                            //System.out.println((String) jcb1.getSelectedItem()+" "+y);

                            //System.out.println((String) jcb1.getSelectedItem() + " " + y);
                            Available ava = new Available(n, b, g, a, d, m, blgr, bgs, x, y);
                            ava.setVisible(true);
                            ava.pack();
                            ava.setLocationRelativeTo(null);
                            ava.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                            Price pr = new Price(x, y);

                            //pr.setVisible(true);
                        } else if (p < q) {
                            Available ava = new Available(n, b, g, a, d, m, blgr, bgs, x, y);
                            ava.setVisible(true);
                            ava.pack();
                            ava.setLocationRelativeTo(null);
                            ava.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                            Price pr = new Price(x, y);
                        }

                    } else {
                        NotFound nf = new NotFound();
                        nf.setVisible(true);
                        nf.pack();
                        nf.setLocationRelativeTo(null);
                        nf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                }
            }
        } catch (Exception e) {
            //e.setStackTrace(null);
            System.out.println(e);
        } finally {
            s.close();
        }
        // Price  pr = new Price(String x, int y);
    }//GEN-LAST:event_jbtnOKMouseClicked

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        LogInUser liu = new LogInUser();
        liu.setVisible(true);
        liu.pack();
        liu.setLocationRelativeTo(null);
        liu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1st;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JComboBox<String> jcb1;
    private javax.swing.JLabel jlBG;
    private javax.swing.JLabel jlBag;
    private javax.swing.JTextField jnumBag;
    // End of variables declaration//GEN-END:variables
}
